require("j3nko.plugins-setup")
require("j3nko.core.options")
require("j3nko.core.keymaps")
require("j3nko.core.user-commands")
require("j3nko.core.colorscheme")

require("j3nko.plugins.gitgutter")
require("j3nko.plugins.harpoon")
require("j3nko.plugins.nvim-tree")
require("j3nko.plugins.quick-scope")
require("j3nko.plugins.vim-test")
require("j3nko.plugins.treesitter")
require("j3nko.plugins.nvim-cmp")
require("j3nko.plugins.lualine")
require("j3nko.plugins.telescope")
-- require("j3nko.plugins.dap")

-- require("j3nko.plugins.coc")
require("j3nko.plugins.lsp")
require("j3nko.plugins.autosave")
