require("j3nko.plugins-setup")
require("j3nko.core.options")
require("j3nko.core.keymaps")
require("j3nko.core.colorscheme")

require("j3nko.plugins.gitgutter")
require("j3nko.plugins.harpoon")
require("j3nko.plugins.nvim-tree")
require("j3nko.plugins.quick-scope")
require("j3nko.plugins.vim-test")
require("j3nko.plugins.treesitter")
require("j3nko.plugins.nvim-cmp")
require("j3nko.plugins.lualine")
require("j3nko.plugins.telescope")

require("j3nko.plugins.nvim-cmp")

require("j3nko.plugins.lsp.lspconfig")
require("j3nko.plugins.lsp.lspsaga")
require("j3nko.plugins.lsp.mason")
require("j3nko.plugins.lsp.null-ls")
